// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zVen6nwhn8H84IXzS5iSc8lXCS-8IK8',
    appId: '1:335700159514:web:3f6ede8a6e46eccbcc35a3',
    messagingSenderId: '335700159514',
    projectId: 'userphin827',
    authDomain: 'userphin827.firebaseapp.com',
    storageBucket: 'userphin827.appspot.com',
    measurementId: 'G-SE3EV9DRKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkEhSlbopVjnD7QoyY7BQ57ymbEoAzDoI',
    appId: '1:335700159514:android:1453eb4b4c523a21cc35a3',
    messagingSenderId: '335700159514',
    projectId: 'userphin827',
    storageBucket: 'userphin827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA95GPOXp30T8MMMfj-BB_20q37C4vqey0',
    appId: '1:335700159514:ios:046fa73b1e089fe8cc35a3',
    messagingSenderId: '335700159514',
    projectId: 'userphin827',
    storageBucket: 'userphin827.appspot.com',
    iosClientId: '335700159514-i1ktb6o68tn0akj59lu4bf5b6ili1j4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.userphin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA95GPOXp30T8MMMfj-BB_20q37C4vqey0',
    appId: '1:335700159514:ios:68676138a3559e24cc35a3',
    messagingSenderId: '335700159514',
    projectId: 'userphin827',
    storageBucket: 'userphin827.appspot.com',
    iosClientId: '335700159514-lsunei5nbt69spapdd1lcpgq8fqlctog.apps.googleusercontent.com',
    iosBundleId: 'com.example.userphin.RunnerTests',
  );
}
